# Generated by Django 5.0 on 2024-01-25 01:50

import apps.products.models.category
import apps.products.models.product
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(editable=False, verbose_name="Updated"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "image",
                    models.ImageField(
                        unique=True,
                        upload_to=apps.products.models.category._image_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "permissions": [
                    ("create_category", "Create category"),
                    ("list_category", "List category"),
                    ("view_category", "View category"),
                    ("change_category", "Change category"),
                ],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(editable=False, verbose_name="Updated"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        unique=True,
                        upload_to=apps.products.models.product._image_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "permissions": [
                    ("create_product", "Create product"),
                    ("list_product", "List product"),
                    ("view_product", "View product"),
                    ("change_product", "Change product"),
                ],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                check=models.Q(("name__ne", "")),
                name="products_category_name_not_empty_check",
                violation_error_message="Name can't be empty.",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 1)), name="products_product_price_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("name__ne", "")),
                name="products_product_name_not_empty_check",
                violation_error_message="Name can't be empty.",
            ),
        ),
    ]
