# Generated by Django 5.0.3 on 2024-03-21 17:26

import apps.products.models.category
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                unique=True,
                upload_to=apps.products.models.category._image_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Image",
            ),
        ),
    ]
