# Generated by Django 5.0.3 on 2024-04-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_order_transactions_order_code_valid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="issued_at",
        ),
    ]
