# Generated by Django 5.0.3 on 2024-04-25 01:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_price"),
        ("tables", "0002_alter_table_code"),
        ("transactions", "0004_remove_order_issued_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(
                default=1,
                help_text="The product quantity must be between 1 and 7",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Price",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1), ("quantity__lte", 7)),
                name="transactions_order_quantity_check",
                violation_error_message="Invalid quantity.",
            ),
        ),
    ]
