# Generated by Django 5.0.3 on 2024-05-09 00:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_alter_table_code"),
        ("transactions", "0005_order_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(editable=False, verbose_name="Updated"),
                ),
                (
                    "total",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Total price",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[("CASH", "Cash"), ("CARD", "Card")],
                        verbose_name="Payment type",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tables.table"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "permissions": [
                    ("create_payment", "Create payment"),
                    ("list_payment", "List payment"),
                    ("view_payment", "View payment"),
                    ("change_payment", "Change payment"),
                ],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("total__gte", 100)),
                name="transactions_payment_total_check",
            ),
        ),
    ]
