# Generated by Django 5.0.3 on 2024-05-09 01:05

import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_alter_table_code"),
        ("transactions", "0006_payment_payment_transactions_payment_total_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.AddField(
            model_name="payment",
            name="code",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 5, 9, 1, 5, 22, 228386, tzinfo=datetime.timezone.utc
                ),
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9A-Za-z]{6}$")],
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("code__regex", "^[0-9A-Za-z]{6}$")),
                name="transactions_payment_code_valid",
                violation_error_message="Invalid code.",
            ),
        ),
    ]
