# Generated by Django 5.0.3 on 2024-05-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_alter_table_code"),
        ("transactions", "0007_remove_payment_id_payment_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="tables.table",
            ),
        ),
    ]
