# Generated by Django 5.0.3 on 2024-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="code",
            field=models.CharField(
                help_text="The table code must contain 4 numeric characters and follow a sequence pattern like '000X'.",
                max_length=4,
                unique=True,
                verbose_name="Code",
            ),
        ),
    ]
